# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100, verbose_name='Ügyfél neve')),
                ('customerPhone', models.CharField(max_length=15, verbose_name='Ügyfél telefonszáma')),
                ('customerEmail', models.EmailField(blank=True, max_length=50, verbose_name='Ügyfél e-mail címe')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeName', models.CharField(max_length=100, verbose_name='Iroda')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contactustosolve.Office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerName', models.CharField(max_length=100, verbose_name='Szolgáltató neve')),
                ('contactName', models.CharField(blank=True, max_length=100, verbose_name='Kapcsolattartó neve')),
                ('city', models.CharField(max_length=100, verbose_name='Város')),
                ('address', models.CharField(max_length=100, verbose_name='Cím')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='Telefonszám')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('activity', models.TextField()),
                ('night', models.BooleanField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('monOp', models.TimeField(blank=True, null=True)),
                ('monCl', models.TimeField(blank=True, null=True)),
                ('tueOp', models.TimeField(blank=True, null=True)),
                ('tueCl', models.TimeField(blank=True, null=True)),
                ('wedOp', models.TimeField(blank=True, null=True)),
                ('wedCl', models.TimeField(blank=True, null=True)),
                ('thuOp', models.TimeField(blank=True, null=True)),
                ('thuCl', models.TimeField(blank=True, null=True)),
                ('friOp', models.TimeField(blank=True, null=True)),
                ('friCl', models.TimeField(blank=True, null=True)),
                ('satOp', models.TimeField(blank=True, null=True)),
                ('satCl', models.TimeField(blank=True, null=True)),
                ('sunOp', models.TimeField(blank=True, null=True)),
                ('sunCl', models.TimeField(blank=True, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactustosolve.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutionDateTime', models.DateTimeField(auto_now_add=True)),
                ('closingDateTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=5)),
                ('sendToProvider', models.CharField(max_length=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactustosolve.Customer')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactustosolve.Office')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactustosolve.Provider')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactustosolve.Office'),
        ),
    ]
