# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactustosolve', '0002_auto_20161219_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='closingDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='sendToProvider',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='status',
            field=models.BooleanField(),
        ),
    ]
