# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactustosolve', '0003_auto_20170103_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='sendToProvider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
